export default {
	switch_auto_tade_tip: 'HOLD TO SWITCH AUTO TRADE',
	select_auto_tade_tip: 'SELECT AUTO TRADE LENGTH',
	no_wallet_connected: 'NO WALLET CONNECTED',
	last_results: 'LAST RESULTS',
	last_results: 'LAST STATS:',
	live_stats: 'LIVE STATS:',
	graph_title_suffix: ' LIVE MARKET',
	wait_new_cycle: 'WAIT FOR NEXT ROUND',
	pool_payout_percent_up: 'UP POOL PAYOUT',
	phase_message_confirmed_open: 'MONEY DISTRIBUTION COMPLETE',
	phase_message_confirmed_pending: 'MINING COMPLETED SUCCESSFULLY',
	auto_trade_select_title: 'CHOOSE NUMBER OF TRADES',
	click_hash: 'Click Hash',
	app_header: 'Live Chat Room',
	entry_rate: 'ENTRY RATE',
	expiry_rate: 'EXPIRY RATE',
	connect_wallet_menu_link: 'Connect Your Wallet',
	placing_bet: 'Processing Your Order...',
	place_bet_error: 'INVESTMENT FAILED',
	distributing_winnings: 'DISTRIBUTING PAYOUTS',
	position_opened: "SIGNING CONTRACT",
	position_opened: "SIGNING CONTRACT...",
	waiting_for_round_start: "WAITING FOR MINING",
	audio_select_title: 'WOULD YOU LIKE TO HAVE SOUND?',
	audio_on_btn: 'YES',
	jackpot_head_link: 'DAILY JACKPOT',
	trade_header_earn: 'EARN',
	system_stats_title: 'SYSTEM STATS :',
	system_stats_24h_win_amount: '24H WIN AMOUNT',
	system_stats_24h_win_amount: '24H WIN:',
	system_stats_alltime_win_amount: 'WIN ALL TIME',
	system_stats_24h_turnover: '24H TURNOVER',
	system_stats_live_people: 'LIVE PLAYERS',
	system_stats_24h_turnover: '24H TURNOVER:',
	system_stats_live_people: 'PLAYERS:',
	trade_history: 'Trades History',
	trade_history_title: 'HISTORY',
	position_table_name: 'POOL',
	sharing_links_category: 'Referral Program',
	treasury_menu_link: 'Winning Treasury History',
	my_stats_menu_link: 'My Stats',
	chat_loading: 'Loading Chat...',
	chat_header: 'Live Chat Room',
	tutorial: 'Tutorial'
}
